name: CI

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  vitest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: checkout repository
      uses: actions/checkout@v4
    - name: setup environment
      run: 
        npm install -g pnpm &&
        pnpm install
    - name: Run Vitest Tests
      run: pnpm test:ci
